package main

import (
	"crypto/ed25519"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"errors"
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/cronye/daemon/internal/license"
)

func main() {
	var (
		privateKeyPath string
		licenseID      string
		email          string
		plan           string
		expiresAt      string
		notBefore      string
		deviceLimit    int
	)

	flag.StringVar(&privateKeyPath, "private-key", "", "path to ed25519 private key PEM (PKCS8)")
	flag.StringVar(&licenseID, "license-id", "", "license ID (default autogenerated)")
	flag.StringVar(&email, "email", "", "licensed customer email")
	flag.StringVar(&plan, "plan", "lifetime", "plan name")
	flag.StringVar(&expiresAt, "expires-at", "", "optional RFC3339 expiration")
	flag.StringVar(&notBefore, "not-before", "", "optional RFC3339 not-before")
	flag.IntVar(&deviceLimit, "device-limit", 1, "device count policy for reference")
	flag.Parse()

	if strings.TrimSpace(privateKeyPath) == "" {
		exitErr("private-key is required")
	}
	if strings.TrimSpace(email) == "" {
		exitErr("email is required")
	}
	if strings.TrimSpace(plan) == "" {
		exitErr("plan is required")
	}
	if licenseID == "" {
		licenseID = fmt.Sprintf("lic_%d", time.Now().UTC().UnixNano())
	}
	if expiresAt != "" {
		if _, err := time.Parse(time.RFC3339, expiresAt); err != nil {
			exitErr("expires-at must be RFC3339")
		}
	}
	if notBefore != "" {
		if _, err := time.Parse(time.RFC3339, notBefore); err != nil {
			exitErr("not-before must be RFC3339")
		}
	}

	privateKey, err := readPrivateKey(privateKeyPath)
	if err != nil {
		exitErr(err.Error())
	}

	claims := license.Claims{
		LicenseID:   licenseID,
		Email:       email,
		Plan:        plan,
		IssuedAt:    time.Now().UTC().Format(time.RFC3339),
		NotBefore:   notBefore,
		ExpiresAt:   expiresAt,
		DeviceLimit: deviceLimit,
	}

	token, err := license.SignToken(privateKey, claims)
	if err != nil {
		exitErr(err.Error())
	}

	fmt.Println(token)
}

func readPrivateKey(path string) (ed25519.PrivateKey, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	if block, _ := pem.Decode(content); block != nil {
		parsed, err := x509.ParsePKCS8PrivateKey(block.Bytes)
		if err != nil {
			return nil, err
		}
		key, ok := parsed.(ed25519.PrivateKey)
		if !ok {
			return nil, errors.New("private key is not ed25519")
		}
		return key, nil
	}

	decoded, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(content)))
	if err != nil {
		return nil, errors.New("invalid private key encoding")
	}
	if len(decoded) != ed25519.PrivateKeySize {
		return nil, errors.New("invalid private key size")
	}
	return ed25519.PrivateKey(decoded), nil
}

func exitErr(message string) {
	_, _ = fmt.Fprintln(os.Stderr, "error:", message)
	os.Exit(1)
}
